### ISSUE TITLE
All key bindings and contextual menu options stopped working

### ISSUE THREAD

**Issue by mclassdesigns** [SublimeText/Origami#164]
Hello. Seems something has changed and now Origami is not working. Contextual menu options are greyed out and keybindings don't trigger the commands.

In the console, I see this error:

`reloading python 3.3 plugin Origami.origami
Traceback (most recent call last):
    File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
    File "./python3.3/importlib/__init__.py", line 90, in import_module
    File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
   File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
    File "/Users/figueroa/Library/Application Support/Sublime Text 3/Installed Packages/Origami.sublime-package/origami.py", line 83, in <module>
    File "/Users/figueroa/Library/Application Support/Sublime Text 3/Installed Packages/Origami.sublime-package/origami.py", line 266, in PaneCommand
AttributeError: 'module' object has no attribute 'Layout'`

This may be related to another recent issue with the functionality.

**Comment by rchl** [comment]
Sorry about that. Released https://github.com/SublimeText/Origami/releases/tag/2.2.2 that should be available soon.

**Comment by mclassdesigns** [comment]
No need to apologize. I appreciate your work on this. In the meantime, I disabled auto updates in Sublime and reverted to an older copy of Origami.

Take care!
